# Generated by Django 2.0.dev20170526121352 on 2017-07-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nom Du Groupe')),
                ('email', models.EmailField(max_length=128, verbose_name='Adresse Email Du Groupe')),
                ('aPassword', models.CharField(max_length=64, verbose_name='Mot De Passe Administrateur')),
                ('vPassword', models.CharField(max_length=128, verbose_name='Mot De Passe Visiteur')),
            ],
        ),
    ]
