# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Touurnament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nom du tournoi')),
                ('isStarted', models.BooleanField(verbose_name='commence')),
            ],
        ),
    ]
