# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_tournament_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.SlugField(max_length=64, verbose_name='Nom du tournoi'),
        ),
    ]
