# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20170722_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={'permissions': (('modify_tournament', 'enable user to modify everything about a tournament'),)},
        ),
    ]
