# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20170722_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Node')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Player')),
            ],
        ),
    ]
