# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 23:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20170722_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='website.Player'),
        ),
        migrations.AlterField(
            model_name='node',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to='website.Player'),
        ),
    ]
